### ISSUE TITLE
.acunetix_terial Directory Not Found

### ISSUE THREAD

**Issue by Auip-0x0** [reza-tanha/A-Cracker#1]
<pre>
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

rm: cannot remove '/home/acunetix/.acunetix_trial/data/license/wa_data.dat': No such file or directory
touch: cannot touch '/home/acunetix/.acunetix_trial/data/license/wa_data.dat': No such file or directory
Traceback (most recent call last):
  File "<A-Cracker.py>", line 4, in <module>
  File "<frozen A-Cracker>", line 76, in <module>
  File "<frozen A-Cracker>", line 64, in crack
  File "<frozen A-Cracker>", line 48, in get_v
FileNotFoundError: [Errno 2] No such file or directory: '/home/acunetix/.acunetix_trial/'
</pre>
`/home/acunetix/` **Directories :**
<pre>
.acunetix  .bashrc  .config  .dbeaver4  Desktop  .emacs  .gtkrc-2.0  .kde  .local  .mozilla  .profile  Templates  .vimrc
</pre>

Do you have a solution to this problem?

**Comment by zankoatzanko** [comment]
سلام .

**step 1:** 
بعد از اینکه فایل اول رو دانلود کردید میاید دستور زیر رو میزنید : 
```
sudo chmod +x ./acunetix_trial.sh
sudo ./acunetix_trial.sh
```
**step2**  مراحل نصبش رو برید جلو و بعد از اینکه نصبش تموم شد برید سراغ 

اگه به مشکلی چیز برخوردید مثلا : 
`_Pytransform Error: Marshal loads failed when running A-Cracker.py_`
با  دست رسی روت اجراش کنید حل میشه

**Comment by Auip-0x0** [comment]
> سلام .
> 
> **step 1:**
> بعد از اینکه فایل اول رو دانلود کردید میاید دستور زیر رو میزنید :
> 
> ```
> sudo chmod +x ./acunetix_trial.sh
> sudo ./acunetix_trial.sh
> ```
> 
> **step2** مراحل نصبش رو برید جلو و بعد از اینکه نصبش تموم شد برید سراغ
> 
> اگه به مشکلی چیز برخوردید مثلا :
> `_Pytransform Error: Marshal loads failed when running A-Cracker.py_`
> با دست رسی روت اجراش کنید حل میشه

Hi.
But this error is not related to the access level.

The program does not find that directory.
I've sent **/home/acunetix** content in the first comment.

Do I make that directory manually?
Or the problem with the source code of the application?

**Comment by zankoatzanko** [comment]
مشکل از مرحله اول هستش چون اون فایل  
`./acunetix_trial.sh`
به درستی نصب نشده، اگه نصب بشه این دایرکتوری هایی  که الا تو ارور گفته درست میشن و  دیگه همچین اروری نمیده .

**Comment by Auip-0x0** [comment]
Hmm yes I reinstalled this and it worked this time.
Thank you for the quick response. I'm closing this issue.

**Comment by hothefa1998** [comment]
@SudoerUser 
what is your python3 version because I always get this error
Pytransform Error: The python version in runtime is different from the build time when running A-Cracker.py
